// See https://svelte.dev/docs/kit/types#app.d.ts
// for information about these interfaces
import type { AuthenticatedUser } from '$lib/server/auth/AuthenticatedUser';
import type { AccessEnvironment } from '$lib/server/auth/CloudflareAccessJwtAuthenticationContext';

declare global {
	namespace App {
		interface Platform {
			/**
			 * `Env` (generated by `wrangler types` from `wrangler.jsonc`) only
			 * covers repository-declared bindings/vars. `ACCESS_TEAM_DOMAIN`/
			 * `ACCESS_AUD` are dashboard-only runtime variables that `wrangler
			 * types` cannot discover (TASK-027), so they are composed in here
			 * via the narrow, application-owned `AccessEnvironment` type
			 * rather than hand-duplicated into a parallel `Env` copy.
			 */
			env: Env & AccessEnvironment;
			ctx: ExecutionContext;
			caches: CacheStorage;
			cf?: IncomingRequestCfProperties;
		}

		interface Locals {
			user?: AuthenticatedUser;
		}

		// interface Error {}
		// interface PageData {}
		// interface PageState {}
	}
}

export {};
